apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2

availabilityZones:
  - us-west-2a
  - us-west-2b

iam:
  withOIDC: true

# AWS managed node groups will be in auto-scaling group:
managedNodeGroups:
  - name: private-nodegroup
    labels: { role: workers }
    instanceType: t2.medium
    volumeSize: 10
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    privateNetworking: true
